Adding docker based development env
impulsoteam/comunidadestech pull request #109
Opened 2020-02-28 19:59 UTC by alaxalves

2020-03-02 13:14 UTC, andrecavallari requested changes

2020-03-02 13:14 UTC, andrecavallari commented on docker-compose.yml
> +    image: mongo:4.0.13
O mongodb que está em uso em staging e production é a versão 3.6.9, então seria ideal utilizarmos a mesma no docker

2020-03-02 13:14 UTC, andrecavallari commented on docker-compose.yml
> +    image: node:13
* Ao invés de usarmos um "image" aqui, seria ideal usar um "build: ." com um Dockerfile, e mantém toda configuração do container no Dockerfile ao invés de mantermos aqui
* Dê preferência sempre por utilizar uma versão LTS do node, (12.16.1 é a versão LTS atual), embora eu acredito que em staging e produção esteja rodando a v10.algumacoisa, @marciovsena, se puder confirmar isso pra mim...

2020-03-02 13:14 UTC, andrecavallari commented on docker-compose.yml
> +    command: >
Aqui o ideal é deixar somente o comando "yarn dev", mantendo o "yarn install" dentro do Dockerfile

2020-03-02 13:14 UTC, andrecavallari commented on docker-compose.yml
> +      - yarn_cache:/comunidadestech/node_modules/
Não sei se é o ideal mantermos a pasta node_modules como volume, talvez o ideal fosse até colocar em um arquivo .dockerignore para que não seja utilizado quando for dado build na aplicação

2020-03-02 13:14 UTC, andrecavallari commented on README.md
> +- `docker exec -it ctech-web bash -c "yarn test"` para rodar alguns testes e popular o DB local com algumas comunidades
Testei esse comando aqui e não populou o db local, para popular o db local talvez um arquivo de seed no Dockerfile seja mais apropriado

2020-03-02 13:14 UTC, andrecavallari commented on docker-compose.yml
> +  db:
Talvez seja bom também liberar a porta do mongodb, em desenvolvimento alguém pode querer acessar o banco de dados por alguma aplicação tipo o Robo3T ou MongoDB Compass

2020-03-02 13:20 UTC, andrecavallari commented on docker-compose.yml
> +    image: node:13
Quase esquecendo, procure usar imagens mais leves, normalmente stretch ou alpine são mais enxutas

2020-03-02 13:59 UTC, marciovsena commented on docker-compose.yml
> +    image: node:13
@andrecavallari estamos usando a versão LTS 12.16.1 em produção e staging.

2020-03-02 14:09 UTC, andrecavallari commented on docker-compose.yml
> +    image: node:13
Show, valeu @marciovsena, é a versão LTS, então acredito que a melhor imagem aqui seria a 12.16.1-stretch, já o mongodb eu acredito que a versão mínima seria a 3.6.17, então o ideal seria essa no docker por enquanto

2020-03-03 00:52 UTC, alaxalves commented on docker-compose.yml
> +    image: node:13
@andrecavallari porque definir um Dockerfile se nao temos uma configuração customizada? Ou temos? Eu segui o que estava definido no README.

2020-03-03 13:57 UTC, andrecavallari commented on docker-compose.yml
> +    image: node:13
Não precisa ter uma configuração customizada, o ideal é que a imagem já contenha todos os recursos necessários

2023-07-31 17:34 UTC, closed without merging