Architectural documentation
impulsoteam/comunidadestech pull request #247
Opened 2020-10-11 21:29 UTC by RaquelFonseca

Estou contribuindo com uma documentação (em Markdown) da arquitetura de projeto. (:

2020-10-15 18:44 UTC, marciovsena requested changes

2020-10-15 18:44 UTC, marciovsena commented on architectural-documentation.md
> +- Contato: raquel.fonseca@ccc.ufcg.edu.br
@RaquelFonseca no lugar do seu e-mail, poderia colocar o link do seu github? Atualmente estamos minimizando a utilização de dados pessoais "sensíveis" e e-mails estão na lista. Aleḿ disso, e-mails acadêmicos tendem a ficar obsoletos.  😊

2020-10-16 19:04 UTC, RaquelFonseca commented on architectural-documentation.md
> +- Contato: raquel.fonseca@ccc.ufcg.edu.br
Sim, sim, tem razão.

2020-10-16 19:13 UTC, marciovsena approved these changes

2020-10-19 12:01 UTC, merged