feat: registration button
impulsoteam/comunidadestech pull request #78
Opened 2020-01-28 02:24 UTC by thejullius

Add `cadastrar comunidade` button when user is not logged in,  and:
- redirect user to `/login`;
- after a successful login, the user is redirected to `/cadastrar`;

2020-01-28 02:25 UTC, thejullius commented on components/LoginComponent/index.js
> +export default function Login() {
@marianaviana

2020-01-28 10:38 UTC, theleoad approved these changes

2020-01-28 11:09 UTC, marianaviana approved these changes

2020-01-28 12:40 UTC, omarciovsena requested changes

2020-01-28 12:40 UTC, marciovsena commented on components/Header/index.js
> +            <a href="/singin" className="navbar-item is-hidden-desktop">
@thejullius no lugar de ter código tão semelhantes para os botões, não poderíamos ter uma função que retorna cada um deles. Assim quando alterar a URL ou o texto do botão não corremos o risco de esquecer um deles?

```
getCreateButton = (url, isMobile) => (
  <a href={url} className=`{isMobile ? "button is-primary is-outlined" : "navbar-item is-hidden-desktop"}`>
      <strong>Cadastre uma comunidade</strong>
  </a>
)
```

2020-01-28 12:40 UTC, marciovsena commented on components/Header/index.js
> +                <a href="/singin" className="button is-primary is-outlined">
@thejullius a url correta deveria ser `/sign-in`

2020-01-28 12:41 UTC, marciovsena commented on server/controllers/SessionController.js
> +    const redirectUrl = cookies.previousPage || '/';
:clap:

2020-01-28 12:42 UTC, thejullius commented on server/controllers/SessionController.js
> +    if (!!cookies.previousPage) res.clearCookie('previousPage');
O ideal seria guardar essa informação no frontend. 
Tentei deixar no state do _app.js pra ficar tipo um estado global mas nao da certo. Aparentemente este e qualquer outro componente é desmontado quando vai pra pagina do linkedin, impossibilitando guardar a informação em qualquer lugar do frontend.

2020-01-28 13:23 UTC, marciovsena commented on server/controllers/SessionController.js
> +    if (!!cookies.previousPage) res.clearCookie('previousPage');
@thejullius já guardei no cookie do browser certa vez, assim o frontend tem acesso, mas funcionou perfeitamente pra mim e a solução atual é boa tb.

2020-01-29 13:22 UTC, omarciovsena approved these changes

2020-01-29 13:22 UTC, merged