WIP:  Apply custom error page
impulsoteam/comunidadestech pull request #79
Opened 2020-01-29 13:45 UTC by marianaviana

2020-01-29 20:30 UTC, theleoad commented on components/MenssageComponent/index.js
> +    return (
Nós estamos passando todos os componentes para componentes funcionais. Então seria interessante fazer com essa estrutura para manter o padrão. No próprio `/pages/_error.js` você consegue ver como é a estrutura de um componente funcional.

2020-01-29 20:37 UTC, theleoad commented on components/MenssageComponent/index.js
> +          <div className="msg-box">
Percebi que as classes `.MenssageComponent` e `.msg-box` não recebem nenhum estilo. Então poderiam ser descartadas para o otimizar o código. Existe também um typo na classe `.menssage-content`, acho que seria `.message-content`.

2020-01-29 20:58 UTC, theleoad commented on components/MenssageComponent/styles.js
> +  background-size: cover;
Aqui pode ficar assim: 
`background: url('/static/bg-stars.svg') center center/cover no-repeat;`
`background-color: ${colors.primary};`

P.S.:
Na verdade poderia ficar assim: 
`background: ${colors.primary} url('/static/bg-stars.svg') center center/cover no-repeat;`
Mas o styled-jsx não aceitou passar uma variável para cor nesse caso aí. Vou ver se abro uma issue no repositório deles.

2020-01-29 20:58 UTC, theleoad commented on components/MenssageComponent/styles.js
> +import { fonts, colors } from '/utils/variables';
`fonts` não está sendo usado, pode apagar.

2020-01-29 20:59 UTC, theleoad commented on pages/_error.js
> +import React, { PureComponent } from 'react';
`{ PureComponent }` não está sendo usado aqui, pode apagar.

2020-01-29 21:02 UTC, theleoad commented on pages/comunidade/index.js
>      });
@thejullius, acredito que você poderá ajudar mais com isso aqui. Quando fiz o teste entrando em /dashaboard, ele fica recarregando a página infinitamente. Então não sei qual seria a forma correta de fazer isso aqui.

2020-01-29 21:05 UTC, theleoad requested changes

2020-01-29 21:05 UTC, theleoad commented on components/MenssageComponent/index.js
> +class MenssageComponent extends Component {
Nós estamos passando todos os componentes para componentes funcionais. Então seria interessante fazer com essa estrutura para manter o padrão. No próprio /pages/_error.js você consegue ver como é a estrutura de um componente funcional.

2020-01-29 21:05 UTC, theleoad commented on components/MenssageComponent/index.js
> +          <div className="msg-box">
Percebi que as classes .MenssageComponent e .msg-box não recebem nenhum estilo. Então poderiam ser descartadas para o otimizar o código. Existe também um typo na classe .menssage-content, acho que seria .message-content.

2020-01-29 21:05 UTC, theleoad commented on components/MenssageComponent/styles.js
> +import { fonts, colors } from '/utils/variables';
fonts não está sendo usado, pode apagar.

2020-01-29 21:05 UTC, theleoad commented on pages/_error.js
> +import React, { PureComponent } from 'react';
{ PureComponent } não está sendo usado aqui, pode apagar.

2020-01-29 21:05 UTC, theleoad commented on pages/comunidade/index.js
> +      Location: '_error',
@thejullius, acredito que você poderá ajudar mais com isso aqui. Quando fiz o teste entrando em /dashaboard, ele fica recarregando a página infinitamente. Então não sei qual seria a forma correta de fazer isso aqui.

2020-01-29 21:36 UTC, thejullius commented on pages/_app.js
> +
Pode remover todo esse código, o proprio next faz a logica

2020-01-29 21:39 UTC, thejullius commented on components/MenssageComponent/index.js
> +class MenssageComponent extends Component {
```suggestion
export default function Message({ credentials }) {...}
```
```suggestion
export default function ErrorMessage({ credentials }) {...}
```

2020-01-29 21:43 UTC, thejullius commented on pages/comunidade/index.js
>      });
```suggestion
      Location: '/',
```
Aqui e nos outros casos, a gente ta travando 400 ou 401. Pro erro 404 a gente so precisa criar o component _error.js que o next resolve o resto

2020-01-29 21:44 UTC, thejullius commented on pages/comunidade/index.js
> +      Location: '_error',
```suggestion
      Location: '/',
```
Aqui e nos outros casos, a gente ta travando 400 ou 401. Pro erro 404 a gente so precisa criar o component _error.js que o next resolve o resto

2020-01-29 21:54 UTC, theleoad commented on pages/_app.js
> +
@thejullius nesse caso aí criamos isso para que não mostrasse o Footer nas páginas 404.

2020-01-30 16:37 UTC, thejullius approved these changes

2020-01-30 16:41 UTC, theleoad approved these changes

2020-01-30 17:24 UTC, merged